bump `setup-node`
in CI as of 5 days ago:

```

Run actions/setup-node@v2
Found in cache @ /opt/hostedtoolcache/node/22.14.0/x64
/usr/local/bin/yarn --version
1.22.22
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
Error: Cache service responded with 422
```

Think this is traceable to finally ending setup-node.

Here's usages in metabase/metabase:

```
❯ ag setup-node .github
.github/workflows/rerun-workflows.yml
26:      - uses: actions/setup-node@v4

.github/workflows/e2e-matrix-builder.yml
29:      - uses: actions/setup-node@v4

.github/workflows/e2e-cross-version.yml
127:      - uses: actions/setup-node@v4

.github/workflows/build-for-release.yml
202:      uses: actions/setup-node@v4

.github/actions/prepare-frontend/action.yml
10:      uses: actions/setup-node@v4
```

done in https://github.com/metabase/metabase/pull/38331 in a few
spots. More info here:
https://github.com/actions/toolkit/discussions/1890 (hat tip Ed on the find).